"""Add tagline field to Bundle model

Revision ID: 118859930e81
Revises: 2e8d009ca102
Create Date: 2026-04-02 01:40:35.862648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118859930e81'
down_revision = '2e8d009ca102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bundles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tagline', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bundles', schema=None) as batch_op:
        batch_op.drop_column('tagline')

    # ### end Alembic commands ###
