"""add experience model, product fields, cart experience support

Revision ID: 347e62e1060f
Revises: 118859930e81
Create Date: 2026-04-13 20:08:54.973558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347e62e1060f'
down_revision = '118859930e81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('video_filename', sa.String(length=500), nullable=True),
    sa.Column('image_filename', sa.String(length=500), nullable=True),
    sa.Column('bundle_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('bundles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bundles_experience_type'))
        batch_op.drop_column('experience_type')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_cart_items_experience_id', 'experiences', ['experience_id'], ['id'])

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_order_items_experience_id', 'experiences', ['experience_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('ingredients', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('size', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('strength', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('image_filename', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_filename')
        batch_op.drop_column('strength')
        batch_op.drop_column('size')
        batch_op.drop_column('ingredients')
        batch_op.drop_column('brand')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_items_experience_id', type_='foreignkey')
        batch_op.drop_column('experience_id')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cart_items_experience_id', type_='foreignkey')
        batch_op.drop_column('experience_id')

    with op.batch_alter_table('bundles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_bundles_experience_type'), ['experience_type'], unique=False)

    op.drop_table('experiences')
    # ### end Alembic commands ###
