"""add experience audio and company settings

Revision ID: 3bb2677597cc
Revises: 347e62e1060f
Create Date: 2026-04-27 23:40:53.214224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb2677597cc'
down_revision = '347e62e1060f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=200), nullable=False),
    sa.Column('tagline', sa.String(length=500), nullable=True),
    sa.Column('about_text', sa.Text(), nullable=True),
    sa.Column('terms_text', sa.Text(), nullable=True),
    sa.Column('privacy_text', sa.Text(), nullable=True),
    sa.Column('landing_video_filename', sa.String(length=500), nullable=True),
    sa.Column('landing_audio_filename', sa.String(length=500), nullable=True),
    sa.Column('store_hero_title', sa.String(length=300), nullable=True),
    sa.Column('store_hero_sub', sa.String(length=500), nullable=True),
    sa.Column('store_wisdom_1', sa.String(length=500), nullable=True),
    sa.Column('store_wisdom_2', sa.String(length=500), nullable=True),
    sa.Column('store_wisdom_3', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_filename', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_column('audio_filename')

    op.drop_table('company_settings')
    # ### end Alembic commands ###
