"""add address fields, is_seasonal, seasonal section

Revision ID: e8b1f50d4a95
Revises: b2c3d4e5f6a1
Create Date: 2026-05-03 22:56:24.029595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b1f50d4a95'
down_revision = 'b2c3d4e5f6a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seasonal_section_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('seasonal_section_title', sa.String(length=300), nullable=True))

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_seasonal', sa.Boolean(), nullable=False))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_line1', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('address_line2', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('town', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('province', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=20), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_line1', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('address_line2', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('town', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('province', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('postal_code')
        batch_op.drop_column('province')
        batch_op.drop_column('town')
        batch_op.drop_column('address_line2')
        batch_op.drop_column('address_line1')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('postal_code')
        batch_op.drop_column('province')
        batch_op.drop_column('town')
        batch_op.drop_column('address_line2')
        batch_op.drop_column('address_line1')

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_column('is_seasonal')

    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.drop_column('seasonal_section_title')
        batch_op.drop_column('seasonal_section_enabled')

    # ### end Alembic commands ###
